{- Paths_* file is normally auto generated by cabal.

    This file is only required for development (to provide version),
    for example when using 'ghcid'.
-}

module Paths_vcr where

import           Data.Version

-- | Empty version, for development mode.
version :: Data.Version.Version
version = Data.Version.Version [] []
