stages:
    - build
    - deliver

nix_build:
    stage: build
    script:
        - nix-build --argstr gitrev $CI_COMMIT_SHORT_SHA

mirror latest master:
    stage: deliver
    only:
        - master
    script:
        - set -u
        - mkdir -p $TARGET
        - rm -f $TARGET/latest-master-*
        - nix-build --argstr gitrev $CI_COMMIT_SHORT_SHA
        - nix-store --add-root $TARGET/latest-master-$CI_COMMIT_SHORT_SHA --indirect -r $(readlink result)

mirror manual:
    stage: deliver
    when: manual
    script:
        - set -u
        - mkdir -p $TARGET
        - nix-build --argstr gitrev $CI_COMMIT_SHORT_SHA
        - nix-store --add-root $TARGET/$(readlink result | awk -F"-" '{print $4}')-$CI_COMMIT_SHORT_SHA --indirect -r $(readlink result)

